Added tuyagateway
selfhosters/unRAID-CA-templates pull request #212
Opened 2021-01-13 18:36 UTC by jaburges

2021-01-13 18:37 UTC, jrdnlc commented
Switch base to testing please

2021-01-13 18:42 UTC, jaburges commented
> Switch base to testing please
> 
> Edit: see other templates for xml format as an example. You have entries that are not needed

the Branch stuff? I can remove that

2021-01-13 18:46 UTC, jrdnlc commented
`Timezone` is also not needed as Unraid adds that by default.

2021-01-13 20:51 UTC, jaburges commented
what is best - to push the xml to you or to point in the devs repo?
https://github.com/TradeFace/tuyagateway/blob/development/etc/unraid_template_tuyagateway.xml

2021-01-13 22:19 UTC, Roxedus commented
Re-add the branches :)

In the end the templateurl doesn't matter, however keep it as linking to this repo.

Don't set actual data in the config, lets just rely on defaults.

```xml
<Config Name="MQTT Host" Target="MQTTHOST" Default="127.0.0.1" Mode="" Description="MQTT Host IP" Type="Variable" Display="always" Required="true" Mask="false">127.0.0.1</Config>
```

can just be

```xml
<Config Name="MQTT Host" Target="MQTTHOST" Default="127.0.0.1" Mode="" Description="MQTT Host IP" Type="Variable" Display="always" Required="true" Mask="false"/>
```

2021-01-14 01:14 UTC, Roxedus requested changes

2021-01-14 01:14 UTC, Roxedus commented on templates/tuyagateway.xml
> +  <Config Name="MQTT Host" Target="MQTTHOST" Default="127.0.0.1" Mode="" Description="MQTT Host IP" Type="Variable" Display="always" Required="true" Mask="false"></Config>
```suggestion
  <Config Name="MQTT Host" Target="MQTTHOST" Default="127.0.0.1" Mode="" Description="MQTT Host IP" Type="Variable" Display="always" Required="true" Mask="false"/>
```
For all the configs

2021-01-14 08:51 UTC, Roxedus approved these changes

2021-01-14 08:51 UTC, merged