ProFTPd XML Patch Salt-Password
selfhosters/unRAID-CA-templates pull request #419
Opened 2023-07-25 17:32 UTC by tooliload

Set Salt to same Value (Request in #417)

2023-07-25 17:35 UTC, nwithan8 requested changes

2023-07-25 17:35 UTC, nwithan8 commented on templates/proftpd.xml
> +  <Config Name="VERBOSE" Target="VERBOSE" Default="OFF" Mode="" Description="" Type="Variable" Display="always" Required="false" Mask="false">ON</Config>
Your default value and text value are still mismatched here.

2023-07-25 17:35 UTC, nwithan8 commented
If you commit to the `tooliload-patch-1` branch, it will automatically update this PR. You don't need to open a new one.

2023-08-28 07:22 UTC, Roxedus commented
Required changes not made.

2023-08-28 07:22 UTC, closed without merging