Add GameVault-Backend template
selfhosters/unRAID-CA-templates pull request #426
Opened 2023-08-20 06:40 UTC by nwithan8

This is the variant that requires connecting to a remote Postgres database (https://gamevau.lt/docs/server-docs/setup/#2-create-a-docker-compose-file)

Closes #415

2023-08-28 07:19 UTC, Roxedus requested changes
Template should do better at communicating the requirement of a external database, add a [Requires](https://github.com/selfhosters/unRAID-CA-templates/blob/683470258e0f499289e5678c9ef1f1845e50e7f3/templates/omegabrr.xml#L14) field, as well as mention it in the overview.

2023-12-22 19:01 UTC, Roxedus commented
Postgres warning made it to the wrong file

2024-01-05 07:23 UTC, Roxedus approved these changes

2024-01-05 07:23 UTC, merged

2024-01-19 22:23 UTC, Alfagun74 commented
Greetings @nwithan8 & @Roxedus.

I am the Developer of GameVaults Backend and in the meantime have already added GameVault in all hosting variants to the CA store.

![image](https://github.com/selfhosters/unRAID-CA-templates/assets/22225051/7c3d2ac2-132d-4568-9b51-7615e131d9dc)

I would like to ask you to remove this duplicate unoffical template of my software, as it is not supported by my company but but links to my support channels and website. My users are already confused.

Thank you for your understanding.