feat: add prusa-connect-rtsp
selfhosters/unRAID-CA-templates pull request #445
Opened 2023-12-30 23:40 UTC by beccazero

2023-12-31 13:30 UTC, nwithan8 requested changes

2023-12-31 13:30 UTC, nwithan8 commented on templates/prusa-connect-rtsp.xml
> +  <CPUset/>
There's a lot of unused variables in here that got auto-added by the plugin you likely used to convert an installed Docker container into an Unraid template. Please clean them up :)

2023-12-31 20:08 UTC, beccazero commented
Removed the unused variables.

2024-01-05 00:44 UTC, nwithan8 requested changes

2024-01-05 00:44 UTC, nwithan8 commented on templates/prusa-connect-rtsp.xml
> +  <Environment>
Remove this Environment section.

2024-01-05 00:44 UTC, nwithan8 commented on templates/prusa-connect-rtsp.xml
> +  <DateInstalled>1703979411</DateInstalled>
Remove this

2024-01-05 07:27 UTC, Roxedus commented
LGTM after the requested changes.

2024-05-21 17:57 UTC, nwithan8 commented
Closing due to inactivity

2024-05-21 17:57 UTC, closed without merging