Update Backblaze template
selfhosters/unRAID-CA-templates pull request #477
Opened 2024-02-28 18:55 UTC by smccloud

Add some new variables (DISABLE_AUTOUPDATE, FORCE_LATEST_UPDATE, USER_ID, GROUP_ID, & CLEAN_TMP_DIR), update DISPLAY_WIDTH & DISPLAY_HEIGHT to new defaults.

2024-02-28 19:36 UTC, nwithan8 requested changes

2024-02-28 19:36 UTC, nwithan8 commented on templates/backblaze.xml
> +  <Config Name="Display Width" Target="DISPLAY_WIDTH" Default="900" Mode="" Description="Width (in pixels) of the virtual screen's window." Type="Variable" Display="always" Required="false" Mask="fal
```suggestion
  <Config Name="Display Width" Target="DISPLAY_WIDTH" Default="900" Mode="" Description="Width (in pixels) of the virtual screen's window." Type="Variable" Display="always" Required="false" Mask="false">900</Config>
```

2024-02-28 19:36 UTC, nwithan8 commented on templates/backblaze.xml
> +  <Config Name="Display Height" Target="DISPLAY_HEIGHT" Default="700" Mode="" Description="Height (in pixels) of the virtual screen's window." Type="Variable" Display="always" Required="false" Mask="
```suggestion
  <Config Name="Display Height" Target="DISPLAY_HEIGHT" Default="700" Mode="" Description="Height (in pixels) of the virtual screen's window." Type="Variable" Display="always" Required="false" Mask="false">700</Config>
```

2024-02-28 19:36 UTC, nwithan8 commented on templates/backblaze.xml
>    <Config Name="ENABLE_CJK_FONT" Target="ENABLE_CJK_FONT" Default="" Mode="" Description="When set to 1, open-source computer font WenQuanYi Zen Hei is installed. This font contains a large range of
```suggestion
  <Config Name="ENABLE_CJK_FONT" Target="ENABLE_CJK_FONT" Default="" Mode="" Description="When set to 1, open-source computer font WenQuanYi Zen Hei is installed. This font contains a large range of Chinese/Japanese/Korean characters." Type="Variable" Display="advanced" Required="false" Mask="false"/>
```

2024-02-28 19:36 UTC, nwithan8 commented on templates/backblaze.xml
> +  <Config Name="Disable Autoupdate" Target="DISABLE_AUTOUPDATE" Default="false" Description="Disables the auto-update of the backblaze client to the latest known-good version at the time of the docke
```suggestion
  <Config Name="Disable Autoupdate" Target="DISABLE_AUTOUPDATE" Default="false" Description="Disables the auto-update of the backblaze client to the latest known-good version at the time of the docker version release."  Type="Variable" Display="always" Required="true" Mask="false">false</Config>
```

Should match the `Default` value.

2024-02-29 16:41 UTC, nwithan8 approved these changes

2024-02-29 22:16 UTC, Roxedus approved these changes

2024-02-29 22:16 UTC, merged