Added hass-unraid
selfhosters/unRAID-CA-templates pull request #507
Opened 2024-08-09 18:12 UTC by PilaScat

2024-08-09 18:53 UTC, nwithan8 requested changes

2024-08-09 18:53 UTC, nwithan8 commented on templates/hass-unraid
> +  <Config Name="Timezone" Target="TZ" Default="Europe/Oslo" Mode="" Description="" Type="Variable" Display="always" Required="true" Mask="false">Europe/Oslo</Config>
Remove TZ, Unraid passes this into all Docker containers automatically

2024-08-09 18:53 UTC, nwithan8 commented on templates/hass-unraid
> +  <Config Name="Path" Target="/data" Default="/mnt/user/appdata/hass-unraid" Mode="rw" Description="" Type="Path" Display="always" Required="true" Mask="false">/mnt/user/appdata/hass-unraid</Config>
```suggestion
  <Config Name="Path" Target="/data" Default="/mnt/user/appdata/hass-unraid" Mode="rw" Description="" Type="Path" Display="advanced" Required="true" Mask="false">/mnt/user/appdata/hass-unraid</Config>
```

Appdata config paths should be under Advanced as users are not expected to ever change this.

2024-08-09 18:53 UTC, nwithan8 commented on templates/hass-unraid
> +  <ExtraParams>--restart always</ExtraParams>
Remove these parameters. Restart policies should be handled via the Docker system in Unraid, not on a per-container basis.

2024-08-09 19:17 UTC, nwithan8 approved these changes

2024-08-12 06:05 UTC, Roxedus approved these changes

2024-08-14 17:00 UTC, nwithan8 commented
> do I need to do anything?

The GitHub Action here is stuck unfortunately. I tried to forcibly retrigger it with an empty commit, but no dice.

If you open a new PR with the same code, I'll stamp it and get it merged in, hopefully won't run into the same issue.

2024-08-14 18:09 UTC, merged

2024-08-22 16:44 UTC, PilaScat commented
I don't know why but there isn't in the apps tab

2024-08-22 16:49 UTC, nwithan8 commented
This probably explains why the Action had stalled, the file is missing the `.xml` suffix, so it didn't get picked up in the feed: https://github.com/Squidly271/AppFeed/blob/master/log.txt#L1521

2024-08-22 17:01 UTC, PilaScat commented
I didn't notice, thanks