Create ddns-ipv64.xml
selfhosters/unRAID-CA-templates pull request #525
Opened 2024-10-17 14:20 UTC by TerrierX

This Docker container is a DDNS updater for Free DynDNS - ipv64.net

2024-10-17 14:30 UTC, nwithan8 requested changes

2024-10-17 14:30 UTC, nwithan8 commented on ddns-ipv64.xml
> +  <Config Name="Timezone" Target="TZ" Default="Europe/Berlin" Mode="" Description="Timezone" Type="Variable" Display="always" Required="true" Mask="false"/>
A `TZ` timezone variable automatically gets passed into every Docker container on Unraid, so no need to include it in the configuration.
```suggestion
```

2024-10-17 14:30 UTC, nwithan8 commented on ddns-ipv64.xml
> +  <Config Name="Domain Präfix" Target="DOMAIN_PRAEFIX" Default="" Mode="" Description="YOUR DOMAIN PRAEFIX (subdomain) : &#x26A0;&#xFE0F; Use only one prefix &#x26A0;&#xFE0F; e.g. ddns" Type="Variabl
Not sure if emojis will render properly in the Unraid GUI.

```suggestion
  <Config Name="Domain Präfix" Target="DOMAIN_PRAEFIX" Default="" Mode="" Description="YOUR DOMAIN PRAEFIX (subdomain). Use only one prefix (e.g. ddns)" Type="Variable" Display="always" Required="false" Mask="false"/>
```

2024-10-17 14:30 UTC, nwithan8 commented on ddns-ipv64.xml
> +  <Config Name="IP check" Target="IP_CHECK" Default="yes|no" Mode="" Description="IP CHECK: The IP address of the domain is checked" Type="Variable" Display="always" Required="false" Mask="false"/>
Fields with a dropdown picker should be marked Required, with the default action first in the pipe list.

```suggestion
  <Config Name="IP check" Target="IP_CHECK" Default="yes|no" Mode="" Description="IP CHECK: The IP address of the domain is checked" Type="Variable" Display="always" Required="true" Mask="false"/>
```

2024-10-17 14:30 UTC, nwithan8 commented on ddns-ipv64.xml
> +  <Config Name="Name Server" Target="NAME_SERVER" Default="ns1.ipv64.net" Mode="" Description="NAME_SERVER: : The name server to check the IP address of your domain" Type="Variable" Display="always"
```suggestion
  <Config Name="Name Server" Target="NAME_SERVER" Default="ns1.ipv64.net" Mode="" Description="NAME_SERVER: : The name server to check the IP address of your domain" Type="Variable" Display="always" Required="false" Mask="false">ns1.ipv64.net</Config>
```

2024-10-17 14:30 UTC, nwithan8 commented on ddns-ipv64.xml
> +  <Config Name="Location logs and script" Target="/data" Default="/mnt/user/appdata/ddns-ipv64" Mode="rw" Description="" Type="Path" Display="always" Required="false" Mask="false"/>
```suggestion
  <Config Name="Location logs and script" Target="/data" Default="/mnt/user/appdata/ddns-ipv64" Mode="rw" Description="" Type="Path" Display="advanced-hide" Required="false" Mask="false">/mnt/user/appdata/ddns-ipv64</Config>
```

Config paths for containers stored in the "appdata" folder are typically put in the "advanced" section, as they don't require immediate set-up by the user (given they have a valid default). Marking is as "advanced-hide" will prevent users from being able to delete this config value from the GUI (force them to set it for their own sake).

2024-10-17 14:34 UTC, TerrierX commented
@nwithan8 Thank you for the useful hints that I weren't aware of

2024-10-17 19:37 UTC, nwithan8 requested changes
Sorry, forgot a few things in my last review. After this, it looks good to go from me.

2024-10-17 19:37 UTC, nwithan8 commented on ddns-ipv64.xml
> +  <Config Name="Polling frequency IP address" Target="CRON_TIME" Default="*/15 * * * *" Mode="" Description="Polling frequency of the current IP address" Type="Variable" Display="always" Required="tr
Sorry, forgot about these defaults in my last review.
```suggestion
  <Config Name="Polling frequency IP address" Target="CRON_TIME" Default="*/15 * * * *" Mode="" Description="Polling frequency of the current IP address" Type="Variable" Display="always" Required="true" Mask="false">*/15 * * * *</Config>
```

2024-10-17 19:37 UTC, nwithan8 commented on ddns-ipv64.xml
> +  <Config Name="Polling frequenz Domain" Target="CRON_TIME_DIG" Default="*/30 * * * *" Mode="" Description="Polling frequenz for the domain (dig DOMAIN_IPV64 A)" Type="Variable" Display="always" Requ
```suggestion
  <Config Name="Polling frequenz Domain" Target="CRON_TIME_DIG" Default="*/30 * * * *" Mode="" Description="Polling frequenz for the domain (dig DOMAIN_IPV64 A)" Type="Variable" Display="always" Required="true" Mask="false">*/30 * * * *</Config>
```

2024-10-17 19:37 UTC, nwithan8 commented on ddns-ipv64.xml
> +  <Config Name="Domain Präfix yes|no" Target="DOMAIN_PRAEFIX_YES" Default="yes|no" Mode="" Description="DOMAIN PRAEFIX YES: This means that the domain PRAEFIX is actively used" Type="Variable" Displa
```suggestion
  <Config Name="Domain Präfix yes|no" Target="DOMAIN_PRAEFIX_YES" Default="yes|no" Mode="" Description="DOMAIN PRAEFIX YES: This means that the domain PRAEFIX is actively used" Type="Variable" Display="always" Required="true" Mask="false"/>
```

2024-10-17 19:37 UTC, nwithan8 commented on ddns-ipv64.xml
> +  <Config Name="Location logs and script" Target="/data" Default="/mnt/user/appdata/ddns-ipv64" Mode="rw" Description="" Type="Path" Display="advanced-hide" Required="false" Mask="false">/mnt/user/ap
```suggestion
  <Config Name="Location logs and script" Target="/data" Default="/mnt/user/appdata/ddns-ipv64" Mode="rw" Description="" Type="Path" Display="advanced-hide" Required="true" Mask="false">/mnt/user/appdata/ddns-ipv64</Config>
```

2024-10-18 06:18 UTC, nwithan8 approved these changes

2024-10-18 06:19 UTC, merged